export const authConstants = {
    USER_LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS : 'USER:LOGIN_SUCCESS',
    USER_LOGIN_FAILURE : 'USER:LOGIN_FAILURE',
    USER_LOGOUT_REQUEST : 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS : 'USER:LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE : 'USER:LOGOUT_FAILURE'
}

export const userConstants = {
    GET_REALTIME_USERS_REQUEST : 'GET_REALTIME_USERS_REQUEST',
    GET_REALTIME_USERS_SUCCESS : 'GET_REALTIME_USERS_SUCCESS',
    GET_REALTIME_USERS_CLEAR : 'GET_REALTIME_USERS_CLEAR',
    SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
    GET_REALTIME_MESSAGE_REQUEST: 'GET_REALTIME_MESSAGE_REQUEST',
    GET_REALTIME_MESSAGE_SUCCESS: 'GET_REALTIME_MESSAGE_SUCCESS',
    GET_REALTIME_MESSAGE_FAILURE: 'GET_REALTIME_MESSAGE_FAILURE',
    GET_REALTIME_MESSAGE_CLEAR: 'GET_REALTIME_MESSAGE_CLEAR'
}

export const publicationConstants = {
    SEND_PUBLICATION_REQUEST: 'SEND_PUBLICATION_REQUEST',
    SEND_PUBLICATION_SUCCESSFUL: 'SEND_PUBLICATION_SUCCESSFUL',
    SEND_PUBLICATION_FAILURE: 'SEND_PUBLICATION_FAILURE',
    GET_PUBLICATIONS_REQUEST: 'GET_PUBLICATIONS_REQUEST',
    GET_PUBLICATIONS_SUCCESS: 'GET_PUBLICATIONS_SUCCESS',
    DELETE_PUBLICATION_REQUEST: 'DELETE_PUBLICATION_REQUEST',
    DELETE_PUBLICATION_SUCCESSFUL: 'DELETE_PUBLICATION_SUCCESSFUL',
    DELETE_PUBLICATION_FAILURE: 'DELETE_PUBLICATION_FAILURE'
}

